// Mocks generated by Mockito 5.0.16 from annotations
// in series/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: unnecessary_overrides

import 'dart:async' as _i4;

import 'package:core/domain/entities/movie.dart' as _i6;
import 'package:core/domain/entities/movie_detail.dart' as _i7;
import 'package:core/domain/entities/season_detail.dart' as _i10;
import 'package:core/domain/entities/serie.dart' as _i8;
import 'package:core/domain/entities/serie_detail.dart' as _i9;
import 'package:core/domain/repositories/movie_repository.dart' as _i3;
import 'package:core/utils/failure.dart' as _i5;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:series/domain/usecases/get_on_the_air_series.dart' as _i11;
import 'package:series/domain/usecases/get_popular_series.dart' as _i12;
import 'package:series/domain/usecases/get_serie_detail.dart' as _i15;
import 'package:series/domain/usecases/get_serie_recommendations.dart' as _i16;
import 'package:series/domain/usecases/get_top_rated_series.dart' as _i13;
import 'package:series/domain/usecases/get_watchlist_series.dart' as _i18;
import 'package:series/domain/usecases/get_watchlist_status_series.dart'
    as _i17;
import 'package:series/domain/usecases/remove_watchlist_series.dart' as _i20;
import 'package:series/domain/usecases/save_watchlist_series.dart' as _i19;
import 'package:series/domain/usecases/search_series.dart' as _i14;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

class _FakeMovieRepository_1 extends _i1.Fake implements _i3.MovieRepository {}

/// A class which mocks [MovieRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRepository extends _i1.Mock implements _i3.MovieRepository {
  MockMovieRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>> getWatchlistMovies() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistMovies, []),
          returnValue: Future<_i2.Either<_i5.Failure, List<_i6.Movie>>>.value(
              _FakeEither_0<_i5.Failure, List<_i6.Movie>>())) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i6.Movie>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>> getNowPlayingMovies() =>
      (super.noSuchMethod(Invocation.method(#getNowPlayingMovies, []),
          returnValue: Future<_i2.Either<_i5.Failure, List<_i6.Movie>>>.value(
              _FakeEither_0<_i5.Failure, List<_i6.Movie>>())) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i6.Movie>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>> getPopularMovies() =>
      (super.noSuchMethod(Invocation.method(#getPopularMovies, []),
          returnValue: Future<_i2.Either<_i5.Failure, List<_i6.Movie>>>.value(
              _FakeEither_0<_i5.Failure, List<_i6.Movie>>())) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i6.Movie>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>> getTopRatedMovies() =>
      (super.noSuchMethod(Invocation.method(#getTopRatedMovies, []),
          returnValue: Future<_i2.Either<_i5.Failure, List<_i6.Movie>>>.value(
              _FakeEither_0<_i5.Failure, List<_i6.Movie>>())) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i6.Movie>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.MovieDetail>> getMovieDetail(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieDetail, [id]),
          returnValue: Future<_i2.Either<_i5.Failure, _i7.MovieDetail>>.value(
              _FakeEither_0<_i5.Failure, _i7.MovieDetail>())) as _i4
          .Future<_i2.Either<_i5.Failure, _i7.MovieDetail>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>> getMovieRecommendations(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieRecommendations, [id]),
          returnValue: Future<_i2.Either<_i5.Failure, List<_i6.Movie>>>.value(
              _FakeEither_0<_i5.Failure, List<_i6.Movie>>())) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i6.Movie>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>> searchMovies(
          String? query) =>
      (super.noSuchMethod(Invocation.method(#searchMovies, [query]),
          returnValue: Future<_i2.Either<_i5.Failure, List<_i6.Movie>>>.value(
              _FakeEither_0<_i5.Failure, List<_i6.Movie>>())) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i6.Movie>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> saveWatchlist(
          _i7.MovieDetail? movie) =>
      (super.noSuchMethod(Invocation.method(#saveWatchlist, [movie]),
              returnValue: Future<_i2.Either<_i5.Failure, String>>.value(
                  _FakeEither_0<_i5.Failure, String>()))
          as _i4.Future<_i2.Either<_i5.Failure, String>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> removeWathclist(
          _i7.MovieDetail? movie) =>
      (super.noSuchMethod(Invocation.method(#removeWathclist, [movie]),
              returnValue: Future<_i2.Either<_i5.Failure, String>>.value(
                  _FakeEither_0<_i5.Failure, String>()))
          as _i4.Future<_i2.Either<_i5.Failure, String>>);
  @override
  _i4.Future<bool> isAddedToWatchlist(int? id) =>
      (super.noSuchMethod(Invocation.method(#isAddedToWatchlist, [id]),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.Serie>>> getWatchlistSeries() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistSeries, []),
          returnValue: Future<_i2.Either<_i5.Failure, List<_i8.Serie>>>.value(
              _FakeEither_0<_i5.Failure, List<_i8.Serie>>())) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i8.Serie>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.Serie>>> getOnTheAirSeries() =>
      (super.noSuchMethod(Invocation.method(#getOnTheAirSeries, []),
          returnValue: Future<_i2.Either<_i5.Failure, List<_i8.Serie>>>.value(
              _FakeEither_0<_i5.Failure, List<_i8.Serie>>())) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i8.Serie>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.Serie>>> getPopularSeries() =>
      (super.noSuchMethod(Invocation.method(#getPopularSeries, []),
          returnValue: Future<_i2.Either<_i5.Failure, List<_i8.Serie>>>.value(
              _FakeEither_0<_i5.Failure, List<_i8.Serie>>())) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i8.Serie>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.Serie>>> getTopRatedSeries() =>
      (super.noSuchMethod(Invocation.method(#getTopRatedSeries, []),
          returnValue: Future<_i2.Either<_i5.Failure, List<_i8.Serie>>>.value(
              _FakeEither_0<_i5.Failure, List<_i8.Serie>>())) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i8.Serie>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i9.SeriesDetail>> getSeriesDetail(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#getSeriesDetail, [id]),
          returnValue: Future<_i2.Either<_i5.Failure, _i9.SeriesDetail>>.value(
              _FakeEither_0<_i5.Failure, _i9.SeriesDetail>())) as _i4
          .Future<_i2.Either<_i5.Failure, _i9.SeriesDetail>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.Serie>>> getSeriesRecommendations(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#getSeriesRecommendations, [id]),
          returnValue: Future<_i2.Either<_i5.Failure, List<_i8.Serie>>>.value(
              _FakeEither_0<_i5.Failure, List<_i8.Serie>>())) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i8.Serie>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.Serie>>> searchSeries(
          String? query) =>
      (super.noSuchMethod(Invocation.method(#searchSeries, [query]),
          returnValue: Future<_i2.Either<_i5.Failure, List<_i8.Serie>>>.value(
              _FakeEither_0<_i5.Failure, List<_i8.Serie>>())) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i8.Serie>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> saveWatchlistSeries(
          _i9.SeriesDetail? series) =>
      (super.noSuchMethod(Invocation.method(#saveWatchlistSeries, [series]),
              returnValue: Future<_i2.Either<_i5.Failure, String>>.value(
                  _FakeEither_0<_i5.Failure, String>()))
          as _i4.Future<_i2.Either<_i5.Failure, String>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> removeWathclistSeries(
          _i9.SeriesDetail? series) =>
      (super.noSuchMethod(Invocation.method(#removeWathclistSeries, [series]),
              returnValue: Future<_i2.Either<_i5.Failure, String>>.value(
                  _FakeEither_0<_i5.Failure, String>()))
          as _i4.Future<_i2.Either<_i5.Failure, String>>);
  @override
  _i4.Future<bool> isAddedToWatchlistSeries(int? id) =>
      (super.noSuchMethod(Invocation.method(#isAddedToWatchlistSeries, [id]),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i10.SeasonDetail>> getSeasonDetail(
          int? id, int? seasonNumber) =>
      (super.noSuchMethod(
          Invocation.method(#getSeasonDetail, [id, seasonNumber]),
          returnValue: Future<_i2.Either<_i5.Failure, _i10.SeasonDetail>>.value(
              _FakeEither_0<_i5.Failure, _i10.SeasonDetail>())) as _i4
          .Future<_i2.Either<_i5.Failure, _i10.SeasonDetail>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [GetOnTheAirSeries].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetOnTheAirSeries extends _i1.Mock implements _i11.GetOnTheAirSeries {
  MockGetOnTheAirSeries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.MovieRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeMovieRepository_1()) as _i3.MovieRepository);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.Serie>>> execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []),
          returnValue: Future<_i2.Either<_i5.Failure, List<_i8.Serie>>>.value(
              _FakeEither_0<_i5.Failure, List<_i8.Serie>>())) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i8.Serie>>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [GetPopularSeries].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPopularSeries extends _i1.Mock implements _i12.GetPopularSeries {
  MockGetPopularSeries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.MovieRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeMovieRepository_1()) as _i3.MovieRepository);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.Serie>>> execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []),
          returnValue: Future<_i2.Either<_i5.Failure, List<_i8.Serie>>>.value(
              _FakeEither_0<_i5.Failure, List<_i8.Serie>>())) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i8.Serie>>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [GetTopRatedSeries].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTopRatedSeries extends _i1.Mock implements _i13.GetTopRatedSeries {
  MockGetTopRatedSeries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.MovieRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeMovieRepository_1()) as _i3.MovieRepository);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.Serie>>> execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []),
          returnValue: Future<_i2.Either<_i5.Failure, List<_i8.Serie>>>.value(
              _FakeEither_0<_i5.Failure, List<_i8.Serie>>())) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i8.Serie>>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [SearchSeries].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchSeries extends _i1.Mock implements _i14.SearchSeries {
  MockSearchSeries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.MovieRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeMovieRepository_1()) as _i3.MovieRepository);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.Serie>>> execute(String? query) =>
      (super.noSuchMethod(Invocation.method(#execute, [query]),
          returnValue: Future<_i2.Either<_i5.Failure, List<_i8.Serie>>>.value(
              _FakeEither_0<_i5.Failure, List<_i8.Serie>>())) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i8.Serie>>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [GetSeriesDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSeriesDetail extends _i1.Mock implements _i15.GetSeriesDetail {
  MockGetSeriesDetail() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.MovieRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeMovieRepository_1()) as _i3.MovieRepository);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i9.SeriesDetail>> execute(int? id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
          returnValue: Future<_i2.Either<_i5.Failure, _i9.SeriesDetail>>.value(
              _FakeEither_0<_i5.Failure, _i9.SeriesDetail>())) as _i4
          .Future<_i2.Either<_i5.Failure, _i9.SeriesDetail>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [GetSeriesRecommendations].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSeriesRecommendations extends _i1.Mock
    implements _i16.GetSeriesRecommendations {
  MockGetSeriesRecommendations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.MovieRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeMovieRepository_1()) as _i3.MovieRepository);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.Serie>>> execute(dynamic id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
          returnValue: Future<_i2.Either<_i5.Failure, List<_i8.Serie>>>.value(
              _FakeEither_0<_i5.Failure, List<_i8.Serie>>())) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i8.Serie>>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [GetWatchListStatusSeries].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchListStatusSeries extends _i1.Mock
    implements _i17.GetWatchListStatusSeries {
  MockGetWatchListStatusSeries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.MovieRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeMovieRepository_1()) as _i3.MovieRepository);
  @override
  _i4.Future<bool> execute(int? id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [GetWatchlistSeries].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchlistSeries extends _i1.Mock
    implements _i18.GetWatchlistSeries {
  MockGetWatchlistSeries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.MovieRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeMovieRepository_1()) as _i3.MovieRepository);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.Serie>>> execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []),
          returnValue: Future<_i2.Either<_i5.Failure, List<_i8.Serie>>>.value(
              _FakeEither_0<_i5.Failure, List<_i8.Serie>>())) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i8.Serie>>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [SaveWatchlistSeries].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveWatchlistSeries extends _i1.Mock
    implements _i19.SaveWatchlistSeries {
  MockSaveWatchlistSeries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.MovieRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeMovieRepository_1()) as _i3.MovieRepository);
  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> execute(
          _i9.SeriesDetail? serie) =>
      (super.noSuchMethod(Invocation.method(#execute, [serie]),
              returnValue: Future<_i2.Either<_i5.Failure, String>>.value(
                  _FakeEither_0<_i5.Failure, String>()))
          as _i4.Future<_i2.Either<_i5.Failure, String>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [RemoveWatchlistSeries].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveWatchlistSeries extends _i1.Mock
    implements _i20.RemoveWatchlistSeries {
  MockRemoveWatchlistSeries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.MovieRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeMovieRepository_1()) as _i3.MovieRepository);
  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> execute(
          _i9.SeriesDetail? serie) =>
      (super.noSuchMethod(Invocation.method(#execute, [serie]),
              returnValue: Future<_i2.Either<_i5.Failure, String>>.value(
                  _FakeEither_0<_i5.Failure, String>()))
          as _i4.Future<_i2.Either<_i5.Failure, String>>);
  @override
  String toString() => super.toString();
}
